# 登录错误尝试次数
LOGIN_ERROR_MAX_TIMES = 5

# 登录错误限制的时间, 单位：秒
LOGIN_ERROR_FORBID_TIME = 600


# 文章类别信息的缓存时间, 单位：秒
AREA_INFO_REDIS_CACHE_EXPIRES = 7200

# 首页展示最多的文章数量
HOME_PAGE_MAX_ARTICLES = 5

# 首页文章数据的Redis缓存时间，单位：秒
HOME_PAGE_DATA_REDIS_EXPIRES = 7200

# 文章详情页展示的评论最大数
ARTICLE_DETAIL_COMMENT_DISPLAY_COUNTS = 30

# 文章详情页面数据Redis缓存时间，单位：秒
ARTICLE_DETAIL_REDIS_EXPIRE_SECOND = 7200

# 文章列表页面每页数据容量
ARTICLE_LIST_PAGE_CAPACITY = 2

# 文章列表页面页数缓存时间，单位秒
ARTICLE_LIST_PAGE_REDIS_CACHE_EXPIRES = 7200

